definitions:
  schemas.APIResponse200:
    properties:
      code:
        example: 200
        type: integer
      message:
        example: success
        type: string
    type: object
  schemas.APIResponse400:
    properties:
      code:
        example: 400
        type: integer
      error:
        type: string
      message:
        example: not found
        type: string
    type: object
  schemas.APIResponse404:
    properties:
      code:
        example: 404
        type: integer
      error:
        type: string
      message:
        example: bad request
        type: string
    type: object
  schemas.APIResponseBook:
    properties:
      code:
        example: 200
        type: integer
      data:
        $ref: '#/definitions/schemas.BookResponse'
      message:
        example: success
        type: string
    type: object
  schemas.APIResponseBooks:
    properties:
      code:
        example: 200
        type: integer
      data:
        items:
          $ref: '#/definitions/schemas.BookResponse'
        type: array
      message:
        example: success
        type: string
    type: object
  schemas.BookRequest:
    properties:
      description:
        type: string
      price:
        type: integer
      rating:
        type: integer
      title:
        type: string
    required:
    - price
    - title
    type: object
  schemas.BookResponse:
    properties:
      createdAt:
        type: string
      description:
        type: string
      id:
        type: integer
      price:
        type: integer
      rating:
        type: integer
      updatedAt:
        type: string
    type: object
info:
  contact: {}
paths:
  /books:
    get:
      consumes:
      - application/json
      description: Get all books
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/schemas.APIResponseBooks'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/schemas.APIResponse400'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/schemas.APIResponse404'
      summary: Get all books
      tags:
      - Books
    post:
      consumes:
      - application/json
      description: Post a book
      parameters:
      - description: Body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/schemas.BookRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/schemas.APIResponseBook'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/schemas.APIResponse400'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/schemas.APIResponse404'
      summary: Post a book
      tags:
      - Books
  /books/{id}:
    delete:
      consumes:
      - application/json
      description: Delete book by ID
      parameters:
      - description: Id
        in: path
        name: ID
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/schemas.APIResponse200'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/schemas.APIResponse400'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/schemas.APIResponse404'
      summary: Delete book by ID
      tags:
      - Books
    get:
      consumes:
      - application/json
      description: Find book by ID
      parameters:
      - description: Id
        in: path
        name: ID
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/schemas.APIResponseBook'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/schemas.APIResponse400'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/schemas.APIResponse404'
      summary: Find book by ID
      tags:
      - Books
    put:
      consumes:
      - application/json
      description: Update the book by ID
      parameters:
      - description: Id
        in: path
        name: ID
        required: true
        type: integer
      - description: Body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/schemas.BookRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/schemas.APIResponseBook'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/schemas.APIResponse400'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/schemas.APIResponse404'
      summary: Update the book by ID
      tags:
      - Books
swagger: "2.0"
